version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: schedule-bmstu
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432