version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: schedule-bmstu
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5

#  bot:
#    container_name: schedule-parser-bmstu
#    build:
#     context: .
#      dockerfile: Dockerfile
#    links:
#      - "db:database"
#    depends_on:
#     db:
#       condition: service_healthy
#    env_file:
#      - ./.env
