version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: schedule-bmstu
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASS:-qwerty123}
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    image: schedule-parser-bmstu
    restart: always
    links:
      - "db:database"
      - "cache:cache"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./.env
